feat: Add account derivation type screen to onboarding [ENG-6500] (#922)
* Add account derivation type screen to onboarding

* Fix msg signing

* Bump core

* Refactor account summary in onboarding

* Add comment

* Add RestoreMethodSelector, OtherWalletSelector screens, add ActionCard component

* Improve derivation type selection logic

* Fix flow logic and CSS

* Fix e2e tests

* Update the logos to use SVGs

* Fix wallet exists guard

* Update the wallet buttons UI

* Fix smoke test

* Remove restore flow dots on the top, move Other wallet option to the bottom

* Add a reusable BackButton component

* Fix smoke tests

* seedphrase -> seed phrase

* Add more locale keys for the restore wallet flow

* Add more locale keys for the restore wallet flow

* seedphrase -> seed phrase

* Clean up wallet creation logic

* Update the DerivationTypeSelector screen copy, add a reusable Link component

* Update the PreferredTypeItem component

* Skip the METHOD_SELECTOR step for the wallet restore

* Remove the initialSelectedType prop and related logic

* Set the restoreMethod

* Improve the PreferredTypeItem component

* Comment out the unused screen e2e tests

* Use new core method

* Add back button to restore method

* Add account details screen

* bump core

* Fix text

* Update the derivation path screen description and option buttons

* Deprecate the components/checkBox

* Add the callout to the derivation path selection screen

* Fix the error TS2322

* Comment out the e2e testing code for the skipped UI

* Comment out the e2e testing code for the skipped UI

* Comment out the e2e testing code for the skipped UI

* Add account breakdown balances

* Change unique window logic

* Use scure bip39 and ensure we don't create the wallet until all details are finalised

* Improve account summary retrieval

* Bump core and fix render issue

* Disable manual again

* Fix e2e tests

* Bump core

* Make some style tweaks

* Change to account derivation by default and auto detect for xverse restore

* Automatically show/hide 24 words based on pasted text length

* Change to account derivation default

* Add info msgs

* Update info tip

* Add initialShow24Words param to show 24 words for Leather

* Add OKX Wallet option for the wallet restore

* Make 24 words configurable by wallet

* Update some styles for the PaymentAddressTypeSelector component

* Change steps to a switch

* Update the divider styles

* Fix onboarding guard

* Bump core

* Removed unused args

* Fix copy

* PR fixes

* Use selected account in stx transfer if one not specified in payload

* Bump core major

---------

Co-authored-by: Denys Hriaznov <hriaznov.dev@gmail.com>